apiVersion: apps/v1
kind: Deployment
metadata:
  name: soby-msa-ordering-depl
  namespace: soby-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soby-msa-ordering
  template:
    metadata:
      labels:
        app: soby-msa-ordering
    spec:
      containers:
        - name: soby-order-backend
          image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/soby-msa-order:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: soby-app-secrets
                  key: DB_HOST
            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: soby-app-secrets
                  key: DB_PW
            - name: AWS_KEY
              valueFrom:
                secretKeyRef:
                  name: soby-app-secrets
                  key: AWS_KEY
            - name: AWS_SECRET
              valueFrom:
                secretKeyRef:
                  name: soby-app-secrets
                  key: AWS_SECRET
                # 컨테이너 상태 확인

---
apiVersion: v1
kind: Service
metadata:
  name: soby-msa-ordering-service
  namespace: soby-ns
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: soby-msa-ordering
