apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: soby-ns
spec:
  type: NodePort
  ports:
  # 서비스포트
  - port: 80
  # 팟의 포트
    targetPort: 80
    nodePort: 30082
  selector:
    app: my-nginx